
version: "3"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - mern-app
    # volumes:
    #   - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      # ME_CONFIG_MONGODB_ADMINUSERNAME: root
      # ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
    networks:
      - mern-app
    depends_on:
      - mongo

  postgresql_db:
    container_name: postgresql_db
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    networks:
    - mern-app

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    environment:
    - PGADMIN_DEFAULT_EMAIL=root@root.com
    - PGADMIN_DEFAULT_PASSWORD=root
    ports:
    - "5050:80"
    networks:
    - mern-app
networks:
  mern-app:
    driver: bridge
# volumes:
#   mongo-data:
#     driver: local
