version: '3.8'


services:

    mongo:
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=alhamou
            # - MONGO_INITDB_DATABASE=vorlage
        networks:
          - network-dev
        ports:
        - "27017:27017"
    mongo-express:
        image: mongo-express
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongo
            - ME_CONFIG_MONGODB_ADMINUSERNAME=root
            - ME_CONFIG_MONGODB_ADMINPASSWORD=alhamou
            - ME_CONFIG_MONGODB_PORT=27017
            #- ME_CONFIG_MONGODB_ENABLE_ADMIN=false
            #- ME_CONFIG_MONGODB_AUTH_DATABASE=admin
            #- ME_CONFIG_MONGODB_AUTH_USERNAME=alhamou
            #- ME_CONFIG_MONGODB_AUTH_PASSWORD=alhamou
            #- ME_CONFIG_BASICAUTH_USERNAME=alhamou
            #- ME_CONFIG_BASICAUTH_PASSWORD=alhamou
        depends_on:
            - mongo
        ports:
          - "8888:8081"
        networks:
          - network-dev

    db:
      container_name: postgresql_db
      image: postgres
      environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
        POSTGRES_DB: test_db
      ports:
        - "5432:5432"
      networks:
      - network-dev
      
    pgadmin:
      container_name: pgadmin4
      image: dpage/pgadmin4
      environment:
      - PGADMIN_DEFAULT_EMAIL=root@root.com
      - PGADMIN_DEFAULT_PASSWORD=root
      ports:
      - "5050:80"
      networks:
      - network-dev

networks:

  network-dev:
